resources:
- name: vm-created-by-deployment-manager
  type: compute.v1.instance
  properties:
    zone: australia-southeast1-b
    machineType: zones/australia-southeast1-b/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/debian-cloud/global/images/family/debian-9
    networkInterfaces:
    - network: global/networks/default